Fix bug in ORC with stripe size >= 1Gb
Summary:
If 2 * <stripe_size> is outside the range of ints, ORC uses Integer.MAX_VALUE as the block size when creating a file.

However, Integer.MAX_VALUE isn't divisible by the bytes per  checksum HDFS uses (512 by default) so it throws an exception
java.io.IOException: io.bytes.per.checksum(512) and blockSize(2147483647) do not match. blockSize should be a multiple of io.bytes.per.checksum

To fix this, take the largest value divisible by the bytes per checksum which is less than Integer.MAX_VALUE as the upper bound.

Test Plan:
Ran a test case using 1Gb stripe size on our cluster and verified it works.

Apparently, open source HDFS doesn't have the same check, so I can't make a qfile test for this.

Running ptests.